"""Apply Phase 15 Champions Meta Profile UI changes to app.py.

This script performs two exact, guarded text replacements. It refuses to edit
app.py if the expected anchors are missing or if the patch appears applied.
"""

from pathlib import Path

APP = Path(__file__).with_name("app.py")

IMPORT_ANCHOR = "import pandas as pd\n"
IMPORT_INSERT = '''\ntry:\n    from champions_integration import get_champions_profile\nexcept ImportError:\n    get_champions_profile = None\n'''

FUNCTION_ANCHOR = "# -----------------------------------------------------------------------------\n# 4. INITIALIZE SESSION STATE\n# -----------------------------------------------------------------------------\n"
FUNCTION_INSERT = '''# -----------------------------------------------------------------------------\n# Phase 15: Champions tournament profile display\n# -----------------------------------------------------------------------------\ndef render_champions_tournament_profile(pokemon_name):\n    """Render tournament statistics without changing existing app scoring."""\n    if get_champions_profile is None:\n        return\n\n    try:\n        profile = get_champions_profile(pokemon_name)\n    except Exception:\n        return\n\n    if not profile.get("available"):\n        return\n\n    appearances = int(profile.get("appearances") or 0)\n    wins = int(profile.get("wins") or 0)\n    losses = int(profile.get("losses") or 0)\n    win_rate = profile.get("win_rate")\n    top_cut_rate = profile.get("top_cut_rate")\n    recent_win_rate = profile.get("recent_win_rate")\n    partners = profile.get("partners") or []\n\n    with strlit.expander("🏆 Champions Tournament Profile", expanded=True):\n        strlit.caption("Historical Champions tournament data. This display does not alter the existing Strategizer score.")\n\n        cols = strlit.columns(4)\n        cols[0].metric("Team Appearances", f"{appearances:,}")\n        cols[1].metric("Win Rate", f"{float(win_rate) * 100:.1f}%" if win_rate is not None else "N/A")\n        cols[2].metric("Top-Cut Rate", f"{float(top_cut_rate) * 100:.1f}%" if top_cut_rate is not None else "N/A")\n        cols[3].metric("Recent Win Rate", f"{float(recent_win_rate) * 100:.1f}%" if recent_win_rate is not None else "N/A")\n\n        strlit.caption(f"Tournament game record: {wins:,} wins · {losses:,} losses")\n\n        if partners:\n            strlit.markdown("**Most common tournament partners**")\n            partner_rows = []\n            for partner in partners[:5]:\n                partner_name = partner.get("pokemon")\n                if not partner_name:\n                    continue\n                partner_rows.append({\n                    "Partner": display_name_for_species_key(partner_name) or partner_name,\n                    "Teams Together": int(partner.get("teams_together") or 0),\n                    "Shared Win Rate": f"{float(partner.get('shared_win_rate') or 0) * 100:.1f}%",\n                })\n            if partner_rows:\n                strlit.dataframe(partner_rows, hide_index=True, use_container_width=True)\n        else:\n            strlit.caption("No tournament partner data available.")\n\n'''

CALL_ANCHOR = '''            if not meta:\n                meta = {"tier": "Unknown", "viability": "0 / 100", "teammates": [], "counters": [], "speed_tier": "N/A", "momentum_rating": "N/A", "hazard_utility": "N/A", "offensive_profile": "N/A"}\n\n'''
CALL_INSERT = CALL_ANCHOR + '''            render_champions_tournament_profile(slot_name)\n\n'''


def replace_once(text: str, anchor: str, replacement: str, label: str) -> str:\n    count = text.count(anchor)\n    if count != 1:\n        raise RuntimeError(f"Phase 15 patch anchor '{label}' expected once, found {count}.")\n    return text.replace(anchor, replacement, 1)\n\n\ndef main() -> None:\n    if not APP.exists():\n        raise SystemExit(f"Could not find {APP}")\n\n    text = APP.read_text(encoding="utf-8")\n\n    if "def render_champions_tournament_profile(" in text:\n        raise SystemExit("Phase 15 already appears to be applied; no changes made.")\n\n    text = replace_once(text, IMPORT_ANCHOR, IMPORT_ANCHOR + IMPORT_INSERT, "integration import")\n    text = replace_once(text, FUNCTION_ANCHOR, FUNCTION_INSERT + FUNCTION_ANCHOR, "UI function")\n    text = replace_once(text, CALL_ANCHOR, CALL_INSERT, "UI call")\n\n    APP.write_text(text, encoding="utf-8")\n    print("Phase 15 patch applied successfully to app.py")\n    print("Existing calculate_meta_viability scoring was not modified.")\n\n\nif __name__ == "__main__":\n    main()\n